AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Application Load Balancer Stack
  Creates ALB, Target Group, and HTTP Listener

# ============================================================================
# PARAMETERS
# ============================================================================
Parameters:
  Workstream:
    Type: String
    Description: "Workstream identifier"
  
  AppName:
    Type: String
    Description: "Application name"
  
  Environment:
    Type: String
    AllowedValues: [dev, qa, uat, prod]
    Description: "Environment name"
  
  CostCenter:
    Type: String
    Description: "Cost center for billing"
  
  Owner:
    Type: String
    Description: "Team owner"
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID for the ALB"
  
  PublicSubnetIds:
    Type: String
    Description: "Comma-separated list of public subnet IDs"
  
  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security group ID for ALB"
  
  ContainerPort:
    Type: Number
    Default: 80
    Description: "Container port for target group"

# ============================================================================
# CONDITIONS
# ============================================================================
Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]

# ============================================================================
# RESOURCES
# ============================================================================
Resources:
  # --------------------------------------------------------------------------
  # APPLICATION LOAD BALANCER
  # --------------------------------------------------------------------------
  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      # Naming: hq-edm-customapps-dev-alb = 26 chars (max 32)
      Name: !Sub "hq-${Workstream}-${AppName}-${Environment}-alb"
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Subnets: !Split [",", !Ref PublicSubnetIds]
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "60"
        - Key: deletion_protection.enabled
          Value: !If [IsProd, "true", "false"]
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: "true"
        - Key: routing.http2.enabled
          Value: "true"
      Tags:
        - Key: Name
          Value: !Sub "hq-${Workstream}-${AppName}-${Environment}-alb"
        - Key: Environment
          Value: !Ref Environment
        - Key: Workstream
          Value: !Ref Workstream
        - Key: AppName
          Value: !Ref AppName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: "CloudFormation"
        - Key: StackName
          Value: !Ref AWS::StackName

  # --------------------------------------------------------------------------
  # TARGET GROUP (32 char limit)
  # --------------------------------------------------------------------------
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      # Naming: hq-edm-customapps-dev-tg = 25 chars (max 32)
      Name: !Sub "hq-${Workstream}-${AppName}-${Environment}-tg"
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: !Ref ContainerPort
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200-399'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: "30"
        - Key: stickiness.enabled
          Value: "false"
      Tags:
        - Key: Name
          Value: !Sub "hq-${Workstream}-${AppName}-${Environment}-tg"
        - Key: Environment
          Value: !Ref Environment
        - Key: Workstream
          Value: !Ref Workstream
        - Key: AppName
          Value: !Ref AppName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Owner
          Value: !Ref Owner
        - Key: ManagedBy
          Value: "CloudFormation"
        - Key: StackName
          Value: !Ref AWS::StackName

  # --------------------------------------------------------------------------
  # HTTP LISTENER
  # --------------------------------------------------------------------------
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

# ============================================================================
# OUTPUTS
# ============================================================================
Outputs:
  AlbArn:
    Description: "ALB ARN"
    Value: !Ref Alb
    Export:
      Name: !Sub "${AWS::StackName}-AlbArn"

  AlbDnsName:
    Description: "ALB DNS Name"
    Value: !GetAtt Alb.DNSName
    Export:
      Name: !Sub "${AWS::StackName}-AlbDnsName"

  AlbHostedZoneId:
    Description: "ALB Hosted Zone ID"
    Value: !GetAtt Alb.CanonicalHostedZoneID
    Export:
      Name: !Sub "${AWS::StackName}-AlbHostedZoneId"

  HttpListenerArn:
    Description: "HTTP Listener ARN"
    Value: !Ref HttpListener
    Export:
      Name: !Sub "${AWS::StackName}-HttpListenerArn"

  TargetGroupArn:
    Description: "Target Group ARN"
    Value: !Ref TargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroupArn"

  TargetGroupName:
    Description: "Target Group Name"
    Value: !GetAtt TargetGroup.TargetGroupName
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroupName"
