AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secrets Manager and Systems Manager Parameter Store - Naming Convention: av-edm/cicd/<purpose> - Contains: JFrog Artifactory credentials, DockerHub credentials, OIDC credentials'

Parameters:
  Workstream:
    Type: String
    Description: "Workstream identifier"

  AppName:
    Type: String
    Description: "Application name"

  Environment:
    Type: String
    Description: "Environment name"
    AllowedValues: [dev, qa, uat, prod]

  CostCenter:
    Type: String
    Description: "Cost center for tagging"

  Owner:
    Type: String
    Description: "Owner for tagging"

  ArtifactoryUsername:
    Type: String
    Description: "JFrog Artifactory username"
    NoEcho: true

  ArtifactoryPassword:
    Type: String
    Description: "JFrog Artifactory password"
    NoEcho: true

  ArtifactoryUrl:
    Type: String
    Description: "JFrog Artifactory URL"

  DockerHubUsername:
    Type: String
    Description: "DockerHub username"

  DockerHubToken:
    Type: String
    Description: "DockerHub access token"
    NoEcho: true

  OIDCClientId:
    Type: String
    Description: "OIDC Client ID"

  OIDCClientSecret:
    Type: String
    Description: "OIDC Client Secret"
    NoEcho: true

Resources:
  # Artifactory Credentials Secret
  ArtifactorySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "av-edm/cicd/streamlit-docker-artifactory"
      Description: "JFrog Artifactory credentials for Streamlit Docker images"
      SecretString: !Sub |
        {
          "username": "${ArtifactoryUsername}",
          "password": "${ArtifactoryPassword}",
          "url": "${ArtifactoryUrl}"
        }
      Tags:
        - Key: Name
          Value: !Sub "av-edm-cicd-artifactory-secret-${Environment}"
        - Key: Environment
          Value: !Ref Environment
        - Key: Workstream
          Value: !Ref Workstream
        - Key: AppName
          Value: !Ref AppName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Owner
          Value: !Ref Owner

  # OIDC Credentials Secret
  OIDCCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "av-edm/cicd/streamlit-OIDC-credentials"
      Description: "OIDC credentials for Streamlit application"
      SecretString: !Sub |
        {
          "client_id": "${OIDCClientId}",
          "client_secret": "${OIDCClientSecret}"
        }
      Tags:
        - Key: Name
          Value: !Sub "av-edm-cicd-oidc-secret-${Environment}"
        - Key: Environment
          Value: !Ref Environment
        - Key: Workstream
          Value: !Ref Workstream
        - Key: AppName
          Value: !Ref AppName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Owner
          Value: !Ref Owner

  # Parameter Store - DockerHub Token
  DockerHubTokenParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/av-edm/cicd/dockerhub-token"
      Description: "DockerHub access token"
      Type: "String"
      Value: !Ref DockerHubToken
      Tags:
        Name: !Sub "av-edm-cicd-dockerhub-token-${Environment}"
        Environment: !Ref Environment
        Workstream: !Ref Workstream
        AppName: !Ref AppName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner

  # Parameter Store - DockerHub Username
  DockerHubUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/av-edm/cicd/dockerhub-user"
      Description: "DockerHub username"
      Type: "String"
      Value: !Ref DockerHubUsername
      Tags:
        Name: !Sub "av-edm-cicd-dockerhub-user-${Environment}"
        Environment: !Ref Environment
        Workstream: !Ref Workstream
        AppName: !Ref AppName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner

  # Parameter Store - Artifactory Username
  ArtifactoryUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/av-edm/cicd/streamlit-docker-artifactory-user"
      Description: "JFrog Artifactory username"
      Type: "String"
      Value: !Ref ArtifactoryUsername
      Tags:
        Name: !Sub "av-edm-cicd-artifactory-user-${Environment}"
        Environment: !Ref Environment
        Workstream: !Ref Workstream
        AppName: !Ref AppName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner

  # Parameter Store - Artifactory API Key
  ArtifactoryApiKeyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/av-edm/cicd/streamlit-docker-artifactory-api-key"
      Description: "JFrog Artifactory API key"
      Type: "String"
      Value: !Ref ArtifactoryPassword
      Tags:
        Name: !Sub "av-edm-cicd-artifactory-apikey-${Environment}"
        Environment: !Ref Environment
        Workstream: !Ref Workstream
        AppName: !Ref AppName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner

  # Parameter Store - Artifactory URL
  ArtifactoryUrlParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/av-edm/cicd/streamlit-docker-artifactory-url"
      Description: "JFrog Artifactory URL"
      Type: "String"
      Value: !Ref ArtifactoryUrl
      Tags:
        Name: !Sub "av-edm-cicd-artifactory-url-${Environment}"
        Environment: !Ref Environment
        Workstream: !Ref Workstream
        AppName: !Ref AppName
        CostCenter: !Ref CostCenter
        Owner: !Ref Owner

Outputs:
  ArtifactorySecretArn:
    Description: "ARN of Artifactory credentials secret"
    Value: !Ref ArtifactorySecret
    Export:
      Name: !Sub "${AWS::StackName}-ArtifactorySecretArn"

  OIDCCredentialsSecretArn:
    Description: "ARN of OIDC credentials secret"
    Value: !Ref OIDCCredentialsSecret
    Export:
      Name: !Sub "${AWS::StackName}-OIDCSecretArn"

  DockerHubTokenParameterName:
    Description: "Parameter Store name for DockerHub token"
    Value: !Ref DockerHubTokenParameter

  ArtifactoryUrlParameterName:
    Description: "Parameter Store name for Artifactory URL"
    Value: !Ref ArtifactoryUrlParameter
